name: test

on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Bandit
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install bandit

      - name: Run Bandit
        run: |
          bandit app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .

  download:
    runs-on: ubuntu-latest
    needs: test  # Ensures this job runs after the 'test' job
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: my-artifact
          path: .
